name: Deploy Documentation

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'Doxyfile'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz
      
      - name: Generate Documentation
        run: |
          make doxygen
      
      - name: Deploy to GitHub Pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/html
          branch: gh-pages-documentation
          target-folder: documentation
          clean: true 