# Votre workflow file devrait ressembler à ceci:
name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Ajoutez cette section de permissions
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  github-pages:
    runs-on: ubuntu-latest
    # Ajoutez cette configuration d'environnement
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      - uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment  # Ajoutez cet ID pour référencer l'étape
        if: github.event_name == 'push'
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
