name: Windows Build at Midnight

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

env:
  BUILD_TYPE: Release
  PROJECT_NAME: ICPocket

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true

    - name: Setup Git LFS
      run: |
        git lfs install
        git lfs track "*.zip"
        git add .gitattributes

    - name: Check for today's commits
      id: check_commits
      shell: bash
      run: |
        TODAY=$(date -u +%Y-%m-%d)
        COMMITS_TODAY=$(git log --since="$TODAY 00:00:00" --until="$TODAY 23:59:59" --oneline)
        if [ -n "$COMMITS_TODAY" ]; then
          echo "HAS_COMMITS=true" >> $GITHUB_ENV
        else
          echo "HAS_COMMITS=false" >> $GITHUB_ENV
        fi

    - name: Setup MSYS2
      if: env.HAS_COMMITS == 'true'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_image
          mingw-w64-x86_64-SDL2_mixer
          mingw-w64-x86_64-SDL2_ttf
          zip
          make

    - name: Build
      if: env.HAS_COMMITS == 'true'
      shell: msys2 {0}
      run: |
        mkdir -p bin/windows
        
        if [ -f "Makefile" ]; then
          make package-windows
        else
          gcc -o bin/windows/${{ env.PROJECT_NAME }}.exe \
            main.c src/*.c \
            -I./include \
            -I/mingw64/include/SDL2 \
            -L/mingw64/lib \
            -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf \
            -mwindows \
            -O2
        fi

    - name: Package
      if: env.HAS_COMMITS == 'true'
      shell: msys2 {0}
      run: |
        DLLS=(
          "SDL2.dll"
          "SDL2_image.dll"
          "SDL2_mixer.dll"
          "SDL2_ttf.dll"
          "libpng16-16.dll"
          "zlib1.dll"
          "libjpeg-8.dll"
          "libfreetype-6.dll"
        )
        
        for dll in "${DLLS[@]}"; do
          if [ -f "/mingw64/bin/$dll" ]; then
            cp -v "/mingw64/bin/$dll" bin/windows/
          fi
        done
        
        echo "@echo off" > bin/windows/launch.bat
        echo "cd %~dp0" >> bin/windows/launch.bat
        echo "start ${{ env.PROJECT_NAME }}.exe %*" >> bin/windows/launch.bat
        
        # Créer une archive plus petite
        cd bin
        zip -9 -r ../${{ env.PROJECT_NAME }}-windows.zip windows/ ../assets/ ../data/ ../README.md
        cd ..

    - name: Split ZIP if needed
      if: env.HAS_COMMITS == 'true'
      shell: bash
      run: |
        ZIP_SIZE=$(stat -f %z "${{ env.PROJECT_NAME }}-windows.zip" 2>/dev/null || stat -c %s "${{ env.PROJECT_NAME }}-windows.zip")
        if [ $ZIP_SIZE -gt 95000000 ]; then
          echo "Splitting ZIP file..."
          split -b 95m "${{ env.PROJECT_NAME }}-windows.zip" "${{ env.PROJECT_NAME }}-windows.zip.part"
        fi

    - name: Commit and Push
      if: env.HAS_COMMITS == 'true'
      shell: bash
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Ajouter les fichiers divisés s'ils existent
        if [ -f "${{ env.PROJECT_NAME }}-windows.zip.partaa" ]; then
          for part in ${{ env.PROJECT_NAME }}-windows.zip.part*; do
            git lfs track "$part"
            git add "$part"
          done
        else
          git lfs track "${{ env.PROJECT_NAME }}-windows.zip"
          git add "${{ env.PROJECT_NAME }}-windows.zip"
        fi
        
        git add .gitattributes
        git commit -m "📦 Windows build $(date -u +%Y-%m-%d)"
        git push origin main --force

    - name: Upload to Artifacts
      if: env.HAS_COMMITS == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-Windows
        path: ${{ env.PROJECT_NAME }}-windows.zip*
        retention-days: 5

    - name: Cleanup
      if: always()
      shell: bash
      run: |
        rm -rf bin/
        rm -f *.zip*
